kind: pipeline
type: docker
name: slack_notify

steps:
- name: partymaker_version_tag_testnet
  image: alpine
  commands:
  - cat version > .tags
  - echo "Current version tag is :" && cat .tags
  when:
    branch: master

- name: partymaker_version_tag
  image: alpine
  commands:
  - echo "$(cat version)-testnet" > .tags
  - echo "Current version tag is :" && cat .tags
  when:
    branch: testnet
    
- name: create_github_release_test
  image: ubuntu:19.04
  environment:
    GITHUB_TOKEN:
      from_secret: github_oauth2_token_for_releases
  commands:
    - apt-get update && apt-get install -y hub git
    - hub release create -m "HollaEx Kit v$(cat .tags) Release" -t ${DRONE_BRANCH} $(cat .tags)
  when:
    branch: master
  
- name: slack_noti_to_releases
  image: bitholla/devops-tools:drone_partymaker-0.1.4
  environment:
    WEBHOOK_URL:
      from_secret: webhook_url
  when:
    status: [success]

trigger:
  branch:
  - master
  - testnet
  event:
  - push