kind: pipeline
type: docker
name: slack_notify

steps:
- name: partymaker_version_tag
  image: alpine
  commands:
  - cat version > .tags
  - echo "Current version tag is :" && cat .tags
  
- name: slack_noti_to_releases
  image: bitholla/devops-tools:drone_partymaker-0.1.4
  environment:
    WEBHOOK_URL:
      from_secret: webhook_url
  when:
    status: [success]

trigger:
  branch:
  - develop
  event:
  - push