paths:
  /chart:
    x-swagger-router-controller: public
    get:
      description: Get trade history HOLCV
      operationId: getChart
      tags:
        - Public
        - Chart
      parameters:
        - in: query
          name: from
          description: Start Date
          required: true
          type: string
        - in: query
          name: to
          description: End data
          required: true
          type: string
        - in: query
          name: symbol
          description: trading pair symbol
          required: true
          type: string
        - in: query
          name: resolution
          description: time interval resolution (1d 1W etc)
          required: true
          type: string
      responses:
        200:
          description: Success
          schema:
            $ref: "#/definitions/TradeDataResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/MessageResponse"
  /charts:
    x-swagger-router-controller: public
    get:
      description: Get trade history HOLCV for all pairs
      operationId: getCharts
      tags:
        - Public
        - Chart
      parameters:
        - in: query
          name: from
          description: Start Date
          required: true
          type: string
        - in: query
          name: to
          description: End data
          required: true
          type: string
        - in: query
          name: resolution
          description: time interval resolution (1d 1W etc)
          required: true
          type: string
      responses:
        200:
          description: Success
          schema:
            $ref: "#/definitions/ObjectResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/MessageResponse"
  