# For the users who what to run web as standalone

version: '3'
services:
  hex-web:
    image: bitholla/hex-web:custom
    build:
      context: .
      dockerfile: docker/Dockerfile
    restart: always
    ports:
      - 80:80
    environment:
      - PUBLIC_URL=https://hex.exchange
      - REACT_APP_PUBLIC_URL=api.hex.exchange
      - REACT_APP_SERVER_ENDPOINT=api.hex.exchange
      - REACT_APP_NETWORK=testnet
      - REACT_APP_CAPTCHA_SITE_KEY=
      - REACT_APP_DEFAULT_LANGUAGE=en
      - REACT_APP_DEFAULT_COUNTRY=KR
      - REACT_APP_BASE_CURRENCY=usdt
  
  

